name: Build and deploy test

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build-and-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
    - name: Build SQLite database
      run: |
        sqlite-utils insert history_books/data.db books popular-history-books.csv --csv File
    - name: Deploy to vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel data.db \
          --project history-books \
          --metadata metadata.json
