name: Build and deploy test

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build-and-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
    - name: Build SQLite database
      run: bash ./build-db-test.sh
    - name: Overwrite file
      uses: "DamianReeves/write-file-action@master"
      with:
        path: ./data.db
        write-mode: overwrite
        contents: 'data.db'
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
