name: Build and deploy

on:
  workflow_dispatch:
  workflow_run: # Would have been simpler to trigger via push but this didn't work when the push originated with a repository_dispath webhook event so changed to run on completion of csv update action
    workflows: ["Fetch CSV from Google Sheets"]
    types:
      - completed

jobs:
  build-and-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build SQLite database
      run: bash ./build-db.sh
    - name: Deploy to vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel ./data.db \
          --token $VERCEL_TOKEN \
          --project history-books \
          --metadata metadata.json # \
#          --vercel-json=vercel.json
